/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 space2.glb 
Author: silvercrow101 (https://sketchfab.com/silvercrow101)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-boi-f6a8c6a6727b4f2cb020c8b50bb2ee60
Title: space boi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Space2(props) {
  const { nodes, materials } = useGLTF('/space2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.waves_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.019]} />
      <mesh geometry={nodes.waves1_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.019]} />
      <mesh geometry={nodes.waves2_Material002_0.geometry} material={materials['Material.002']} position={[0.925, 0.155, 0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.019]} />
      <mesh geometry={nodes.particles_Material002_0.geometry} material={materials['Material.002']} position={[4.897, 7.938, 3.553]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.204} />
      <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} position={[3.755, 4.279, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.624} />
      <mesh geometry={nodes.Sphere005_Material001_0.geometry} material={materials['Material.001']} position={[-3.42, 4.602, -1.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.624} />
      <mesh geometry={nodes.Sphere004_Material002_0.geometry} material={materials['Material.002']} position={[3.755, 4.279, 0]} rotation={[-0.688, 0, 0]} scale={[1.041, 0.816, 0]} />
      <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} position={[0, -1.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[11.2, 11.2, 1]} />
      <mesh geometry={nodes.Sphere002_Material001_0.geometry} material={materials['Material.001']} position={[-3.574, 3.926, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />
      <mesh geometry={nodes.Sphere007_Material001_0.geometry} material={materials['Material.001']} position={[1.996, 5.669, -2.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />
      <mesh geometry={nodes.Sphere002_Material002_0.geometry} material={materials['Material.002']} position={[-3.574, 3.926, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />
      <mesh geometry={nodes.Sphere007_Material002_0.geometry} material={materials['Material.002']} position={[1.996, 5.669, -2.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />
      <mesh geometry={nodes.Sphere003_Material002_0.geometry} material={materials['Material.002']} position={[-3.574, 3.926, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.411} />
      <mesh geometry={nodes.Sphere008_Material002_0.geometry} material={materials['Material.002']} position={[1.996, 5.669, -2.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.411} />
      <instancedMesh args={[nodes.Sphere001_Material002_0.geometry, materials['Material.002'], 5]} instanceMatrix={nodes.Sphere001_Material002_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/space2.glb')
